//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLSnipServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangeData
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public int RangeId { get; set; }
        public string Address { get; set; }
    }
}
