//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLSnipServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRange
    {
        public int Id { get; set; }
        public string RangeName { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string AllowedUsers { get; set; }
    }
}
